# Generated by Django 5.0.6 on 2024-07-02 03:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shorts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('publish_date', models.DateTimeField(default=datetime.datetime(2024, 7, 2, 8, 55, 20, 887213))),
                ('content', models.CharField(max_length=500)),
                ('actual_content_link', models.CharField(max_length=200)),
                ('image', models.CharField(default=None, max_length=100)),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
            ],
        ),
    ]
