# Generated by Django 5.0.6 on 2024-07-02 03:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorts',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 2, 9, 12, 19, 723999)),
        ),
    ]
