# Generated by Django 5.0.6 on 2024-07-02 03:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_shorts_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorts',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 2, 9, 21, 37, 608139)),
        ),
    ]
